# Generated by Django 4.2.27 on 2026-01-09 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condutores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='condutor',
            old_name='nome_completo',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='condutor',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='condutor',
            name='categoria_cnh',
        ),
        migrations.RemoveField(
            model_name='condutor',
            name='cnh',
        ),
        migrations.RemoveField(
            model_name='condutor',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='condutor',
            name='data_nascimento',
        ),
        migrations.AddField(
            model_name='condutor',
            name='cargo',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='condutor',
            name='equipamento',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='condutor',
            name='filial',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='condutor',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='condutores/'),
        ),
        migrations.AlterField(
            model_name='condutor',
            name='empresa',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
