# Generated by Django 4.2.27 on 2026-01-09 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condutores', '0002_rename_nome_completo_condutor_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condutor',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
