# Generated by Django 4.2.27 on 2026-01-09 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('condutores', '0003_alter_condutor_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cnh_em_dia', models.BooleanField()),
                ('clrv_em_dia', models.BooleanField()),
                ('experiencia_duas_caixas', models.BooleanField()),
                ('transmissao_correta', models.BooleanField()),
                ('checagem_geral', models.BooleanField()),
                ('sistema_freios', models.BooleanField()),
                ('regulagem_retrovisores', models.BooleanField()),
                ('observa_ambiente', models.BooleanField()),
                ('antecipa_paradas', models.BooleanField()),
                ('freia_suavemente', models.BooleanField()),
                ('distancia_adequada', models.BooleanField()),
                ('respeita_sinalizacao', models.BooleanField()),
                ('analisa_espaco', models.BooleanField()),
                ('distancia_seguranca', models.BooleanField()),
                ('atencao_trafego', models.BooleanField()),
                ('velocidade_adequada', models.BooleanField()),
                ('volante_ambas_maos', models.BooleanField()),
                ('centrado_faixa', models.BooleanField()),
                ('usa_retrovisores', models.BooleanField()),
                ('usa_buzina', models.BooleanField()),
                ('sinaliza_faixa', models.BooleanField()),
                ('sinaliza_pedestres', models.BooleanField()),
                ('tempo_semaforo', models.BooleanField()),
                ('sinaliza_saidas', models.BooleanField()),
                ('respeita_preferencial', models.BooleanField()),
                ('sinaliza_conversao', models.BooleanField()),
                ('faixa_antecipada', models.BooleanField()),
                ('conversao_correta', models.BooleanField()),
                ('velocidade_conversao', models.BooleanField()),
                ('convergencia_suave', models.BooleanField()),
                ('retrovisores_ultrapassagem', models.BooleanField()),
                ('sinaliza_ultrapassagem', models.BooleanField()),
                ('buzina_ultrapassagem', models.BooleanField()),
                ('visibilidade_via', models.BooleanField()),
                ('retorno_seguro', models.BooleanField()),
                ('tolerancia', models.BooleanField()),
                ('tranquilidade', models.BooleanField()),
                ('cinto', models.BooleanField()),
                ('paciencia', models.BooleanField()),
                ('responsabilidade', models.BooleanField()),
                ('observacoes', models.CharField(blank=True, max_length=300)),
                ('resultado', models.CharField(choices=[('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado')], max_length=10)),
                ('condutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condutores.condutor')),
            ],
        ),
    ]
